version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      ACCEPT_EULA: "${ACCEPT}"
      SA_PASSWORD: "${PWD}"
      MSSQL_PID: ${PID}
    ports:
      - "1433:1433"
  tickets-project:
    build: .
    ports: 
      - "7075:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
